version: '3'
services:
  app:
    container_name: laravel-example  
    build: ./laravel/php
    volumes:
      - .:/var/www
  nginx:
    image: nginx 
    container_name: nginx
    ports:
      - 8082:80 
    volumes:
      - .:/var/www
      - ./laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    platform: 'linux/amd64'
    image: mysql:5.7 
    container_name: laravel-db
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./laravel/db/data:/var/lib/mysql
      - ./laravel/db/my.cnf:/etc/mysql/conf.d/my.cnf 
      - ./laravel/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3321:3306